package edu.kit.ipd.creativecrowd.transformer;



import edu.kit.ipd.chimpalot.util.Logger;
import edu.kit.ipd.creativecrowd.crowdplatform.PlatformIdentity;
/**
 * This Class is responsible for generating a unique ID for an Experiment by combining the ID's
 * generated through the ID responses from the used Crowdplatforms and extracting the correlating
 * ID for a Platform from the MainID. 
 * @author Robin
 *
 */
public class IDGenerator {

    /**
     * This Generator is only used in the transformer package and should not be visible to 
     * any components outside the package, therefore it is protected.
     */
    protected IDGenerator() {

    }
    /**
     * This method extracts the ID of a platform from the MainID. It has to be possible 
     * to withdraw that information and all IDs, even when there is only one platform 
     * present, must contain the separation symbol (|) to distinguish between platform name
     * and generated ID. Each platform id pair needs to be introduced with a (?) question 
     * mark so that it is possible to distinguish between id and next platform id.
     * 
     * @param mainID The ID from which the corresponding ID is to be extracted.
     * @param pID the Platform to whom the ID should correspond to.
     * @return the ID for the Platform.
     */
    protected String getID(String mainID, PlatformIdentity pID) {
    	if(mainID == null) {
    		Logger.log("main ID is null");
    		return null;
    	}
    	Logger.debug(Integer.toString(mainID.indexOf(pID.toString())));
    	if(mainID.indexOf(pID.toString()) == -1) {
    		Logger.log("The Platform " + pID.toString() + " is not represented in the main String: " + mainID);
    		//Give back the mainID, there seems to be a mistake.
    		return mainID;
    	}
        String resultID = mainID.substring(mainID.indexOf(pID.toString()));
        if(resultID.contains("|")) {
        	resultID = resultID.substring(resultID.indexOf("|") + 1);
        }
        if(resultID.contains("?")) {
        	resultID = resultID.substring(0, resultID.indexOf("?"));
        }
        return resultID;
    }
    
    /**
     * This method generates the MainID by concatenating all platforms names with their corresponding
     * ID. In Order to separate the platform name from the ID the Symbol (|) is used. As of now there
     * is no separating symbol between multiple platforms (Ex.: {platform}|ID_{platform2}|ID). It is 
     * necessary that the separating symbol is added before this method is called.
     * 
     * @param ids The Ids generated by the platforms. They must contain the separation Symbol
     * @return the concatenated ID.
     */
    protected String getMainID(Iterable<String> ids) {
        StringBuffer buff = new StringBuffer();
        for(String s : ids) {

            buff.append(s);
        }

        return buff.toString();
        
    }
}
